unique_ids:
  assets:
    standard-page.html: IRFNKSLOXS2WK56DLSSAMTP2FVT4UZQR
    theme.css: ANXTKAOQ3YM5TZDNL4ZJCENACPYDRY64
  forms:
    Form1: WICEVWX2UJSISHH3HKLVYDDXE3S5U7LR
  modules: {}
  scripts: {}
  server_modules: {}
